version: 6.0.1311.{build}
branches:
  only:
  - master
image: Visual Studio 2019
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
- cmd: >-
    buildV6 1272 %APPVEYOR_BUILD_NUMBER%

    buildV6 1311 %APPVEYOR_BUILD_NUMBER%

    buildV365 3454 %APPVEYOR_BUILD_NUMBER%
artifacts:
- path: '*.exe'
